/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XDR_H_RPCGEN
#define _XDR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct NomeFile {
	char lettera[255];
};
typedef struct NomeFile NomeFile;

struct Lista {
	int numeroFile;
	NomeFile nomeFile[8];
};
typedef struct Lista Lista;

struct InfoFile {
	int caratteri;
	int parole;
	int linee;
};
typedef struct InfoFile InfoFile;

struct InputDir {
	char *dir;
	int soglia;
};
typedef struct InputDir InputDir;

#define REMOTE 0x20000015
#define REMOTEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILE_SCAN 1
extern  InfoFile * file_scan_1(char **, CLIENT *);
extern  InfoFile * file_scan_1_svc(char **, struct svc_req *);
#define DIR_SCAN 2
extern  Lista * dir_scan_1(InputDir *, CLIENT *);
extern  Lista * dir_scan_1_svc(InputDir *, struct svc_req *);
extern int remote_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILE_SCAN 1
extern  InfoFile * file_scan_1();
extern  InfoFile * file_scan_1_svc();
#define DIR_SCAN 2
extern  Lista * dir_scan_1();
extern  Lista * dir_scan_1_svc();
extern int remote_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_NomeFile (XDR *, NomeFile*);
extern  bool_t xdr_Lista (XDR *, Lista*);
extern  bool_t xdr_InfoFile (XDR *, InfoFile*);
extern  bool_t xdr_InputDir (XDR *, InputDir*);

#else /* K&R C */
extern bool_t xdr_NomeFile ();
extern bool_t xdr_Lista ();
extern bool_t xdr_InfoFile ();
extern bool_t xdr_InputDir ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XDR_H_RPCGEN */
